### ISSUE TITLE
Upon start getting strict error

### ISSUE THREAD

**Issue by chrisseldo** [ccoenraets/react-university#1]
Everything goes smoothly until I use `npm start` or `node server.js`

Here's the error:

```
let db = require('./pghelper');
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/usernamehere/Desktop/react-university/server.js:4:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by ccoenraets** [comment]
Did you upgrade to Node 4.x?
